#docker-compose -f docker/dev/docker-compose.yml up
version: '3'
services:
  blog:
    build: .
    ports:
        - 81:80
    volumes:
        - ../../:/var/www
        - ../uploads:/media/uploads
    command: /usr/sbin/apache2ctl -D FOREGROUND
    environment:
      - "DATABASE_PASSWORD=12345"
      - “DATABASE_USER=mysql_user"
      - "DATABASE_HOST=mysql"
      - "DATABASE_DB_NAME=site"
  mysql:
      image: mysql
      ports:
          - 6603:3306
      environment:
        MYSQL_ROOT_PASSWORD: "12345"
      volumes:
          - ../data:/var/lib/mysql